confirm-before-quit = false
padding-x = 12
padding-y = [7, 3]
theme = "catppuccin-mocha"

[developer]
enable-log-file = true

[colors]
cursor = "#CBA6F7"
vi-cursor = "#F5C2E7"

[cursor]
shape = "beam"
blinking = true
blinking-interval = 400

[editor]
program = "emacs"
args = []

[fonts]
family = "JetBrainsMono Nerd Font"
use-drawable-chars = true
features = ["ss02", "ss03", "ss05", "ss19"]

[fonts.emoji]
family = "Noto Color Emoji"

[navigation]
mode = "Plain"
use-split = false

[renderer]
backend = "Automatic"
disable-unfocused-render = true
performance = "High"
target-fps = 60

[shell]
program = "zsh"
args = ["-l"]

[title]
content = "(/>w<)/ Terminal - {{ ABSOLUTE_PATH }}"
placeholder = "(/>w<)/"

[window]
blur = true
opacity = 0.8
width = 1280
height = 720
windows-corner-preference = "Round"
